#!/bin/bash

echo "🚀 Football-Migu 后端 Railway 部署指南"
echo "===================================="
echo ""
echo "Railway 是一个简单的云平台，支持 Python 应用，提供免费套餐。"
echo ""
echo "📋 部署步骤："
echo ""
echo "1. 访问 Railway 并登录："
echo "   https://railway.app"
echo ""
echo "2. 创建新项目："
echo "   - 点击 'New Project'"
echo "   - 选择 'Deploy from GitHub repo'"
echo "   - 授权 Railway 访问你的 GitHub"
echo "   - 选择 'football-migu' 仓库"
echo ""
echo "3. Railway 会自动检测到 railway.json 配置文件"
echo ""
echo "4. 环境变量已在 railway.json 中配置："
echo "   - HOST: 0.0.0.0"
echo "   - PORT: 由 Railway 自动分配"
echo "   - ENVIRONMENT: production"
echo "   - DATABASE_URL: sqlite:///data/football_betting.db"
echo "   - BACKEND_CORS_ORIGINS: 包含 Vercel 前端 URL"
echo ""
echo "5. 部署完成后，Railway 会提供一个 URL，例如："
echo "   https://football-migu-backend.up.railway.app"
echo ""
echo "6. 更新前端的环境变量："
echo "   访问: https://vercel.com/jasonyins-projects/frontend/settings/environment-variables"
echo "   更新 NEXT_PUBLIC_API_URL 为 Railway 后端 URL + /api/v1"
echo ""
echo "📌 备选方案：使用 Railway CLI"
echo ""
echo "如果你想使用命令行部署："
echo ""
echo "# 安装 Railway CLI"
echo "npm install -g @railway/cli"
echo ""
echo "# 登录"
echo "railway login"
echo ""
echo "# 初始化项目"
echo "railway link"
echo ""
echo "# 部署"
echo "railway up"
echo ""
echo "按 Enter 继续..."
read