# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install fastapi uvicorn sqlalchemy pydantic pydantic-settings python-dotenv"]

[start]
cmd = "python main.py"